### PR TITLE
Show transponder code in GTX330 display

### PR DESCRIPTION
**Pull request by SebDieBln**
The transponder code is read from `/instrumentation/transponder/id-code`~~, but only if it is valid (`/instrumentation/transponder/goodcode`)~~.

(see #4)

### CODE REVIEW

**Comment by SebDieBln** [comment]
Please note that FlightGear in the current version (2016.1.1) does not set these properties (and is misbehaving when reading them). I added a [merge request addressing these issues](https://sourceforge.net/p/flightgear/fgdata/merge-requests/60/).

**Comment by SebDieBln** [comment]
@HHS81 Should we implement a workaround for the above mentioned bug? E.g. reading the transponder code directly from the `/instrumentation/transponder/inputs/digit` properties?

**Comment by HHS81** [comment]
Hmmm... somehow I don't see any numbers, since the property `/instrumentation/transponder/goodcode` is never be valid.

You should announce the merge request on the devel-list, since I had the experience that it might be overseen. 
I think until that a workaround would be o.k.

**Comment by HHS81** [comment]
You might wanna check [this code from the Extra500](https://sourceforge.net/p/flightgear/fgaddon/HEAD/tree/trunk/Aircraft/extra500/Nasal/AvidyneEntegra9/keypad.nas) beginning at line 214.

**Comment by SebDieBln** [comment]
You are right. Without my patch to FlightGear the _Radio frequencies_ dialog never sets the `id-code` nor the `goodcode`, so the GTX330 does not show any numbers. I will go for the workaround then, it shouldn't be too hard.

If I understand the code of the Extra500 correctly, it reads and sets `id-code` only. So changing the code via the dialog should have no effect on the Extra 500 either?
When the buttons of the GTX330 become functional, the code will be written to the mentioned properties and it will be shown on the display.

Nonetheless I will ask the FG-devs what the `goodcode` is actually supposed to mean and how to deal with it.

**Comment by HHS81** [comment]
`goodcode` is something which is not hardcoded, and comes from the author [Gary Neely](http://www.buckarooshangar.com/flightgear/index.html) as he provided a KT-76c Transponder under GNU GPL. 

Changing the code via dialog is possible in the Extra500, but I'm not sure if everything needed for is in the script I linked.

**Comment by SebDieBln** [comment]
Thanks for the hint about `goodcode`. I removed the logic that expected it to be set.

I also added a workaround so that changes to the digits inside the _Radio Frequencies_ dialog will trigger a redraw of the display.

**Comment by HHS81** [comment]
As I understood, `goodcode` is true when all 4 numbers had been selected via the keys and with that  the squawk is complete. So if true, the digits will be shown in the _Radio Frequencies dialog_.

Reading the manual of the GTX330 the real behavior is a bit different, as in the KT-76c.

**Pull request merged**
