### PR TITLE
Issue #22 

### PR DESCRIPTION
**Pull request by HHS81**
Updates the reflection shader so it uses real fresnel effect. Colors and reflections looks now more realistic.

### CODE REVIEW

**Comment by SebDieBln** [comment]
On my system the color of the windows changed to something quite yellow. I am using rembrandt-rendering.
Checking with the default-renderer the color is still shifted to yellow, although not so much as with the rembrandt-rendering.

fgfs-screen-001
(Screenshot using rembrandt-rendering)

**Comment by HHS81** [comment]
Hmmm...was the previous Cubemap better?
It seems the shader is broken for non-transparent surfaces in Rembrandt!?

**Comment by SebDieBln** [comment]
> Was the previous Cubemap better?

Yes, it was better. See the attached screenshot. And the default renderer also renders the windows slightly in yellow with the new shader. So I guess Rembrandt is just amplifying the effect, but it is not the cause.

fgfs-screen-001
(Screenshot using rembrandt-rendering, using master 7576f414dba75bded53098412a0bfe72c6606903)

**Comment by HHS81** [comment]
hmmm... o.k. I must admit I have a from of Red–green color blindness, so I have problems to distinguish greenish colors from yellow etc.... For me it looked green, not yellow.

O.k. I will change the cubemap back, and adjust the values.

**Review by SebDieBln — COMMENTED** [review]
May I propose to change the description of this and the following commits to have the reference to the issue in the second line? Most tools (including GitHub) display only the first line of the description by default in lists and overviews.

**Comment by HHS81** [comment]
> May I propose to change the description of this and the following commits to have the reference to the issue in the second line? Most tools (including GitHub) display only the first line of the description by default in lists and overviews.

The next commits I will do

**Comment by HHS81** [comment]
I changed back the cubemap, it should look now o.k.

**Comment by SebDieBln** [comment]
Looks good, merging now.

**Pull request merged**
